### PR TITLE
Delete entity/POI data

### PR DESCRIPTION
**Pull request by Jikoo**
* Support original `.mcr`
   * Regionerator is not parsing chunk data, so MC Region file formats are supported. The `.mca` format is named after the newer chunk format, not the region file format.
* Delete oversized chunks
   * MC would eventually handle these, but only after the chunk in question was generated and saved. Given that an oversized chunk is at minimum as large as ~200 normal chunks, this is a pretty critical (if niche) disk space saving case.
* Attempt to delete POI/entity data even if region data does not exist
* Fixes RegionInfo reuse always wiping previously wiped pointers
   * Regionerator doesn't reuse these, so it was not affected
* Minor optimizations

TODO
* [x] Include last entity modification as an option for preserving chunks
   * POI data is not useful due to the fact that it's just constructed out of in-world structures; if it has been modified, so has the world.
* [x] Clean up/optimize deletion flow
   * [x] Delete entity/POI data immediately if chunk data is not present rather than verifying
* [x] Optimize I/O
   * Note to self:
     * FileChannel reportedly has around the same performance as RandomAccessFile
     * ByteBuffers are WAY easier to use, less error prone, and more comprehensible than manual parsing
     * AsyncFileChannel may be faster for single thread code (aka Regionerator's deletion thread)

### CODE REVIEW

**Comment by Jikoo** [comment]
Hello and welcome to a ~~long~~ 🔥blazingly🔥 🚀informative🚀 ~~blog post~~ status update.

Did some benchmarking the other day prior to swapping over to NIO:
* Read+Write: FileChannel blows RandomAccessFile out of the water
  * FC is 🔥blazingly🔥 🚀fast🚀
    * Only could have more 🔥blazinglyest🔥 🚀fastosity🚀 if it was [written in Rust(🚀)](https://github.com/mTvare6/hello-world.rs)
    * 4,270% faster than RAF on HDD
    * 1,461% faster than RAF on SSD
  * Honorable mention to AsyncFileChannel for trying
    * Pretty sure now that the person who advocated for it over FileChannel had conflated terms and actually meant that manual sync of a FileChannel for async operations may outperform AsyncFileChannel for async operations.
    * 230% faster than RAF on HDD
    * 113% faster than RAF on SSD
* Read-only: FileChannel and RandomAccessFile perform about the same
  * RAF performed 1-2% faster than FC
  * RAF was more consistent post-warmup with a margin of error of 0.5% to FC's 1.2%
  * RAF had noticeably slower times during warmup (~15% slower vs ~10% slower), making it very possible that RAF will actually perform worse on average
    * Regionerator may perform thousands (depending on world size) of rapid read/write operations, but never millions. These are further diluted by protection plugin queries, so it's possible that the I/O will never become a hot spot.
* Data conversion:
  * ByteBuffers allow direct conversion into correct data types rather than manually parsing a range from a byte[]
    * This fixes certain problems like me parsing a signed int as an unsigned int. This parsing error was never going to be a problem due to the fact that a) it would protect things longer, and b) negative values cannot be put in (real) region files for those values, but the fact remains that I was not parsing certain values correctly.
  * ByteBuffers do require a little extra memory due to the overhead of extra object creation and do perform parsing slower than manual parsing, but this performance hit is minimal compared to the overall speed increase of using NIO. The creation costs of buffers are frontloaded before the time-sensitive I/O starts.

Since I assume most serious people are using far nicer SSDs and CPUs than I have in my rig, I imagine the real-world performance savings of swapping to NIO will only really be about a 200% performance increase over the state prior to this PR after we factor in the fact that we now have to read 3x as many files. Please, if you are running a Minecraft server and have your world stored on a HDD, stop punishing yourself and your players. SSDs are relatively cheap and you'll see a massive performance increase (at least, in load times for generated area) due to reduced I/O times.

The alternative is to not do all the files at once, which is definitely an option, but then we have to do redundant protection checks and cycles take 3x as long. Granted, with the performance boost, we could also just speed up the defaults.

The main blocker for cycle speed is (and always will be) sync hooks. Currently the design is very poor for handling them. I've had a couple ideas for addressing them, but at the end of the day they're going to be bucketed into a sync task that then queries all the protection plugins. I'd probably be more motivated to deal with that if I a) still used Regionerator at all (the last time friends coerced me into managing a server for them we just started a new world) and b) used sync protection hooks (GP may be a dumpster fire, but it's an easy-to-use dumpster fire with a vaguely thread-safe claims list! Pretty much nothing else is thread-safe in any way, but it works for me).

As far as areas this PR needs to address before I'm ready to mark it as ready:
I've converted AnvilRegion over to using the new NIO-based RegionFile, but it constructs 3 copies on the fly when saving, 2 of which are unnecessary. This is technically kinda gross, because all 3 of those are "duplicates" as far as functionality is concerned. The allocation doesn't actually impact the re-read-to-save time, but it is unnecessary. In addition, previously the `AnvilRegion#write` call updated the values identically to `AnvilRegion#read`. For my own purposes this is unnecessary, but it's very possible to introduce this behavior again without causing any performance overhead. At very least we'll get rid of 2 of the copies, possibly work our way back down to a max of 2 header buffers internally.

**Comment by Jikoo** [comment]
Given the number of [silly (and horrible) errors](https://github.com/Jikoo/Regionerator/pull/161/commits/72ca53432ff9a1b3b23f1a7a361705dc5e9f1384#diff-d045e3fb5372648c233855439e5671886dbafa4ccc11c50d016ce697716e25bbR33) I made while prepping this I'm sure there's something I missed, it's almost certainly not production-ready. It is, however, ready to the point where I'm going to have to actually test it, which will likely take me some time to get through because I haven't set up any unit tests for this project.
Regionerator predated my desire for unit tests on everything, and I haven't worked my way around to it. Still rewriting my EnchantableBlocks tests for the 50th time as I finally excise MockBukkit from all my projects.

**Comment by Folas1337** [comment]
I just wanna say, I'm eagerly watching this development and I can't wait for it to finally come true <3
Thanks for keeping at this and being so eager as well, I really appreciate that, keep it up :)

**Comment by Jikoo** [comment]
Sorry, I hit a lot of burn out - testing Regionerator really sucks. Most of it is manual deletion and comparisons against known-good readers' results. I end up writing a lot of throwaway code and doing manual work because I don't have a test suite set up, and while I could fix that, doing so would take time I'm not ready to sink into Regionerator right now. Trying to get motivated again, this is definitely a priority for me.

**Comment by Folas1337** [comment]
No worries, I totally get you, especially with what you're describing.
Take your time to get motivated again and then get back when you feel like it :)

It's mostly a minor issue to me, I got a temporary solution for the time being.

Happy to hear you think this is important :)

**Pull request merged**
